### ISSUE TITLE
Input type range control has wrong value on initial render

### ISSUE THREAD

**Issue by danyx23** [Matt-Esch/virtual-dom#228] opened 2015-04-10 15:18 UTC
When you add an input element of type range (slider control) that has min and max set to non-default values, and use the value attribute to set the initial slider position, then the initial render of virtual-dom will place the slider at a wrong position (in my tests all the way to the left or right). On the first patch application the slider jumps into the right spot, but the initial render is wrong.

See this gist which demonstrates the wrong initial position and that the first patch (after a 3 second delay) fixes it: http://requirebin.com/?gist=e1f8f94771d15d79b983

Encountered this when working with cycle-js. The discussion leading to the discovery of the bug is here: https://github.com/danyx23/cyclejsBMI/issues/1

**Comment by neonstalwart** [comment] 2015-04-10 18:37
this is a similar race condition to what happens when you try to set the value of a `<select>`.  in the case of a `<select>` if you set the `value` before an `<option>` has been added to match that `value` then the `value` will be set to the first `<option>`.  there are [ways to work around this](https://github.com/Matt-Esch/virtual-dom/issues/115#issuecomment-62406607) for a select.

the problem you're up against is that you're setting a `value` and then setting `max` and `min`.  since the `value` is outside the initial range (defined by the initial values of `max` and `min`) your `value` is not applied like you expect.  `value`, `min`, and `max` must be applied according to some order and if you declare `value` after `max` and `min` in your object then it will work:

```js
  return h('input', {
    className: "form-control",
    type: "range",
    min: 120,
    max: 200,
    value: value
  });
```

if you're not comfortable with this approach then you can use a hook to apply the `value` using something like `setTimeout` to ensure that the `value` is applied *after* `min` and `max` have been set.  incidentally, this is why your 2nd render works - `min` and `max` are set to values that will allow `value` to be set.

i don't think virtual-dom can do anything more to help this specifically but this kind of thing is why hooks are available.

**Comment by danyx23** [comment] 2015-04-10 22:19
Oh I see! It never occured to me that the order of the attributes would be significant. Knowing this I can easily work around the issue. Thank you!

**Comment by ivan-kleshnin** [comment] 2015-04-11 08:08
Wait JS objects are unordered by standard. So the problem can't be solved at all :scream: 
http://stackoverflow.com/questions/27906854/object-property-ordering-in-javascript

**Comment by danyx23** [comment] 2015-04-11 08:27
Yes you are of course right, yesterday night when I read the reply I assumed I must have missed something about the order of JS object keys being retained, but yes, it's just a lucky implementation detail that this works. This is not good.

**Comment by ivan-kleshnin** [comment] 2015-04-11 08:48
Yes, I would call this and [this](https://github.com/Matt-Esch/virtual-dom/issues/115#issuecomment-62406607) very dangerous. Lets wait what @Matt-Esch will say. Of course noone is satisfied with `setTimeout` workarounds.

**Comment by neonstalwart** [comment] 2015-04-11 11:33
I know that ordering of keys is not guaranteed and that's why I mentioned hooks. `setTimeout` or `setImmediate` or whatever other mechanisms you want to use to cause a minimal delay is really not problematic when you are already only getting eventual consistency due to the rendering loop.

**Comment by neonstalwart** [comment] 2015-04-11 11:41
...that said, I have previously requested to delay calling hooks until after properties have been set. that would fix this without using any delay. 

another option you have that doesn't use delay or rely on ordering of keys is to use a hook to set `max`, `min`, and `value` in sequence.

**Comment by ivan-kleshnin** [comment] 2015-04-11 11:44
@neonstalwart I see no relation of all this stuff to app code. I want to write JSX with attrs in any order and be sure it will be compiled to correct and environment-agnostic code. If Virtual DOM should do some tricks to make this happen – well it's not fine for devs, but it shouldn't be in app for sure. I'm afraid I'm not interested in remembering all implementation details of VDOM. 

If objects keys are unordered and order matters - VDOM should not use objects. Or apply some heuristics. Or I dunno what. HTML is declarative. Order-dependent stuff is imperative. 
I never heard of order issues with attributes aside of VDOM.

**Comment by ivan-kleshnin** [comment] 2015-04-11 11:53
Anyone knows whether this problem exists in React?

**Comment by danyx23** [comment] 2015-04-11 12:16
I totally agree with @ivan-kleshnin, this kind of thing has to be handled transparently by vdom as a library. Using setTimeout is a horrible workaround.

It seems react doesn't have this problem (e.g. here: http://users.on.net/~mikeandgeminoz/code/react.bootstrap.slidertest/index.html ).

This may be unrelated and just a detail, but when I inspect the dom of the react sample, the <input> element has an explicit attribute for value - in the vdom example in the gist above, the <input> element does not have a value attribute.

**Comment by neonstalwart** [comment] 2015-04-11 12:40
ok so this is simple... the original example is applying properties. as you both probably know, properties and attributes are different. the example works perfectly when you specify attributes instead of properties.

**Comment by neonstalwart** [comment] 2015-04-11 12:42
https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md has a section explaining attributes vs properties.

**Comment by danyx23** [comment] 2015-04-11 12:51
@neonstalwart thanks for your help! This looks promising, but I have to see how to make this work with my use case of JSX and cyclejs custom elements (those excpect values to be handed down as properties, not arguments inside properties).

**Comment by danyx23** [comment] 2015-04-11 12:52
I meant "not attributes inside properties" of course

**Comment by neonstalwart** [comment] 2015-04-11 12:56
ok so I'm closing this and you can work it out with the JSX parser you're using.

**Closed by neonstalwart** 2015-04-11 12:56 UTC

**Comment by danyx23** [comment] 2015-04-11 13:48
Very strange, if I pass the value as an attribute it work in chrome but not firefox for me (both on windows). In firefox it doesn't even get the correct value after the timeout now. 

I made a version of the gist at the beginning of this, but passing everything as attributes:
http://requirebin.com/?gist=2fd44b68a1a1f96a74f6

Can anybody confirm this? If this is indeed a problem with vdom and firefox now I guess I should open a new ticket?

**Comment by ivan-kleshnin** [comment] 2015-04-11 13:52
> Can anybody confirm this? 

Confirmed. In FireFox it behaves differently than in Chrome / Safari.

**Comment by danyx23** [comment] 2015-04-14 21:53
+1 to please reopen. The fact that handing attributes is still order dependent on firefox means that this is not the actual solution to the problem.

**Comment by neonstalwart** [comment] 2015-04-14 22:21
virtual-dom does not attempt to normalize differences between browsers.  it simply provides an implementation of a diff/patch algorithm.  

why can't the JSX parser take responsibility for understanding that an `<input>` with `type: 'range'` needs to apply `value` after `max` and `min`?  why should this be pushed down into virtual-dom?

if you have some properties/attibutes which need to be set in a specific order use a hook to apply those things in the order they need to be applied.  virtual-dom provides you with the pieces you need in order to do that.

if you think that virtual-dom can do better to provide you with what you need, then please make some concrete suggestions.  claims like 

> VDOM breaks standards and relies on implementation specific behavior.

make no sense since virtual-dom is using standard APIs like `document.createElement`, `element.setAttribute`, etc to achieve what it does.  it is those APIs which are not doing what you'd like - see http://requirebin.com/?gist=5c954ed4d1be654a428e for an example using the raw DOM APIs.

**Comment by neonstalwart** [comment] 2015-04-14 22:23
> 1) VDOM props / attributes are order-sensitive
> 2) VDOM expects props / attributes to be passed as unordered JS Object

these 2 things are not true - it is the DOM which is forcing an order, not virtual-dom

**Comment by danyx23** [comment] 2015-04-14 22:47
@neonstalwart I agree that VDOM is not at fault for the underlying problem. However, since it provides an abstraction that does not provide a deterministic way to control the order of application (without hooks), consumers of VDOM can't really create the correct dom behaviour. 

You say
> why can't the JSX parser take responsibility for understanding that an <input> with type: 'range' needs to apply value after max and min?

It seems to me that "apply after" is a bit of a difficult problem with the current VDOM api. Are you suggesting that the JSX parser (or an intermediary layer) add the correct hooks?

**Comment by neonstalwart** [comment] 2015-04-14 23:25
> Are you suggesting that the JSX parser (or an intermediary layer) add the correct hooks?

exactly. virtual-dom is just a building block. it is a low-level API that may have other layers built on top to make it more developer-friendly. virtual-hyperscript is included for convenience but it is not necessarily a comprehensive solution and it is not the primary focus of virtual-dom.

**Comment by ivan-kleshnin** [comment] 2015-04-15 09:40
@neonstalwart the problem is that every next JSX transpiler will be forced to do exactly the same stuff. 
I don't see here any potential for implementation-specific decisions which would justify resending of this problem to the next layer. But it's your right to believe in opposite, I will not insist anymore.

**Comment by neonstalwart** [comment] 2015-04-15 14:41
fwiw, #213 which was just merged allows you to provide a custom `render` function when patching and i believe it would allow you to do some of this kind of customization.

**Comment by dy** [comment] 2018-03-13 22:28
Since problem remains, may I ask what if reordering `apply-properties` so to invoke hooks after setting properties [here](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js#L12-L24) would make sense? A tiny bit of order meaningful for input values and hooks context is good, isn't that so?

I can come up with PR if you will, @Matt-Esch @Raynos @danyx23 @neonstalwart.

**Comment by dy** [comment] 2018-03-16 21:00
@Matt-Esch @Raynos @danyx23 @neonstalwart ping

**Comment by helenCBRE** [comment] 2018-06-18 15:40
Are there still known issues with Firefox not rendering range inputs correctly on the first render? I'm having an issue where my initial render is taking on the min value as opposed to the defined default prop and I'm defining value after min and max. 

And this is only happening to my in Firefox - not in Chrome/Safari or IE.
